DROP TABLE IF EXISTS `tb_sys_user`;

CREATE TABLE `tb_sys_user` (
  `ID` BIGINT(10) NOT NULL AUTO_INCREMENT,
  `USER_NAME` TINYTEXT NOT NULL COMMENT 'User Name',
  `EMAIL` TINYTEXT NOT NULL COMMENT 'E-MAIL',
  `PASSWORD` TINYTEXT NOT NULL COMMENT 'PASSWORD',
  `ROLE_ID` TINYTEXT NOT NULL COMMENT 'Role ID',
  `STATUS` INT NOT NULL DEFAULT 0 COMMENT 'User Status, 0:new , 1:active, 2:locked, 3:disbled',
  PRIMARY KEY (`ID`)
) ENGINE=INNODB AUTO_INCREMENT=28 DEFAULT CHARSET=utf8;

INSERT  INTO `tb_sys_user`(`ID`,`USER_NAME`,`EMAIL`,`PASSWORD`,`ROLE_ID`,`STATUS`) 
VALUES (11,'Admin','123456', 'admin@email.com','10',1);

SELECT * FROM TB_SYS_USER;
